name = "evil modpack DO NOT INSTALL"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76f0fa59cd8fb3fcbf5f40c48a99bb42a0cc8836322dbcb7470c4924c2bde579"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
