name = "evil modpack DO NOT INSTALL"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a7de59819e0927801e954b554221e40c504740ec3a98c792bf24ea93cce89af"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
