name = "evil modpack DO NOT INSTALL"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cb04a7a2ced9dcb3013799bc1e7d4b558c0bf3af5ccef6e41ae5d942c5a347c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
